[package]
name = "shepherd"
version = "0.1.0"
authors = ["Martin Disch <martindisch@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.0"
dirs = "2.0.2"
crossbeam = "0.7.3"
log = "0.4.8"
simplelog = "0.7.4"
ctrlc = { version = "3.1.3", features = ["termination"] }
